config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,contollers:{sessions:"admins/sessions"}
  devise_for :users,controllers:{sessiones:"user/sessions"}
  resources :posts do
    resources :comments
  end
    root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    belongs_to :"user"
    validates_presence_of :title
    validates_presence_of :body
    validates_length_of :title, :in=> 10..50, :message => "longitud no válida"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :auth_user!

  # GET /posts
  # GET /posts.json
  #Nuevo viernes20
    
  def auth_user!
    if admin_signed_in?
      authenticate_admin!
    else
      authenticate_user!
    end
  end
    
  def index
      if admin_signed_in?
          @posts = Post.all
      else
          @posts = current_user.posts
      end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
#    if admin_signed_in?
      if admin_signed_in?
    else
      @post = Post.new
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
    #Se modifico.
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        flash[:success]="Se guardo el post"
        format.html { redirect_to @post}
#        format.html { redirect_to @post, notice: 'Post was successfully created.' }
         format.json { render :show, status: :created, location: @post }
      else
        flash[:alert]='ocurrio un problema al guardar el post.'
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body,)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-6 column">
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title,:class => "validate[required, minSize[8]]" %>
      </div>

      <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body,:class => "validate[required, minSize[10]]" %>
      </div>
        
<!--        Editar el diseño del Botón.-->
    
            <div class="actions">
                <%= f.submit 'Aceptar', :class => 'button small' 'radius' %>
            </div>
        </div>
  </div>
<% end %>

app/views/posts/_navigation.html.erb
<!--Incluya una barra de navegacion usuando el helper link_to-->
<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: false">
    <ul class="title-area">
        <li class="name">
            <h1>Formatos</h1>
        </li>
    </ul>
    
    <section class="top-bar-section">
        <ul class="left">
            <li class="has-dropdown not-click"><a href="#">MENÚ</a>
                <ul class="dropdown" >
                    <li class="parent-link show-for-small-only"><a class="parent-link js-generated" href="#">Formato</a></li>
                    <li><label>Secciones</label></li>
                    <li><%=link_to 'Ver', controller: '/posts', action: 'index' %> </li>
                    <%if user_signed_in? %>
                    <li><%=link_to 'Nuevo', controller: '/posts', action: 'new' %> </li>
                    <% end %>
                    
                </ul>
            </li>
        </ul>
        
        <ul class="right">
            <%if user_signed_in? %>
            <li><a>Bienvenido(a) <%= current_user.email %></a></li>
            <li><%= link_to "Editar", edit_user_registration_path %></li>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete,  :class => 'navbar-link' %></li>
            
            <%elsif admin_signed_in? %>
            <li><a>Bienvenido(a) administrador<%= current_admin.email %></a></li>
            <li><%= link_to "Editar", edit_user_registration_path %></li>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete,  :class => 'navbar-link' %></li>
            
            <% else %>
            <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
            <li><%= link_to "Registrate", new_user_registration_path %></li>
            <% end %>
        
        
        <!--Es para dividir -->
        <li class="divider"></li>
            </ul>
    </section>
</nav>
<!--
Helper hace la transformación de los link_to a <a>-->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <!--Variable desde post controller -->
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
            <% if post.body %>
                <a href="#" data-reveal-id="post-<%= post.id%>">Ver comentarios</a>
            
                <div id="post-<%= post.id%>" class="reveal-modal" data-reveal>
                    <a class="close-reveal-modal">&#215</a>
                    <%= post.body %></td>
            
                    
                </div>
            <% end %> 

    
        <td><%= User.find(post.user_id).email %></td>
       <% if can?  :show, post %>
    <td><%= link_to 'Show', post %></td>
    <% end %>
    
         <% if can? :edit, post %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
         <% end %>
    
         <% if admin_signed_in? %>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     <% end %>

      </tr>
 <% end %>
</tbody>
</table>
<br>


    

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
    <%= render :partial => @post.comments.reverse %>
</div>

<!--Crea un formulario. Ajax este habilitado. Se altera cada elemento del formulario en la variable f-->
<%= form_for([@post, Comment.new], remote: true)do|f|%>
 <p><%=f.label :body,"New comment"%></br>
<%=f.text_area :body %>
</p>
<p><%=f.submit "Add Comment"%></p>
<% end%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>